// Generated by scripts/hangul-coverage.mjs from https://github.com/edwardkim/rhwp v0.8.7 (1a76570e833917d15817415a53c09ad61ab3203f) rhwp-studio/src/command. Do not edit.
export const COMMAND_LABELS: Record<string, { ko: string; en: string; shortcut: string | null }> = {
  "edit:undo": {
    "ko": "되돌리기",
    "en": "Undo",
    "shortcut": "Ctrl+Z"
  },
  "edit:redo": {
    "ko": "다시 실행",
    "en": "Redo",
    "shortcut": "Ctrl+Shift+Z"
  },
  "edit:cut": {
    "ko": "오려 두기",
    "en": "Cut",
    "shortcut": "Ctrl+X"
  },
  "edit:copy": {
    "ko": "복사하기",
    "en": "Copy",
    "shortcut": "Ctrl+C"
  },
  "edit:paste": {
    "ko": "붙이기",
    "en": "Paste",
    "shortcut": "Ctrl+V"
  },
  "edit:format-copy": {
    "ko": "모양 복사",
    "en": "Format Painter",
    "shortcut": "Alt+C"
  },
  "edit:format-paste": {
    "ko": "모양 붙여넣기",
    "en": "Paste Format",
    "shortcut": null
  },
  "edit:delete": {
    "ko": "지우기",
    "en": "Delete",
    "shortcut": "Ctrl+E"
  },
  "edit:select-all": {
    "ko": "모두 선택",
    "en": "Select All",
    "shortcut": "Ctrl+A"
  },
  "edit:find": {
    "ko": "찾기",
    "en": "Find",
    "shortcut": "Ctrl+F"
  },
  "edit:find-replace": {
    "ko": "찾아 바꾸기",
    "en": "Replace",
    "shortcut": "Ctrl+F2"
  },
  "edit:find-again": {
    "ko": "다시 찾기",
    "en": "Find Again",
    "shortcut": "Ctrl+L"
  },
  "edit:compare-documents": {
    "ko": "문서 비교",
    "en": "Compare Documents",
    "shortcut": "Alt+Shift+V"
  },
  "edit:document-history": {
    "ko": "문서 이력 관리",
    "en": "Document History",
    "shortcut": "Ctrl+Shift+H"
  },
  "edit:goto": {
    "ko": "찾아가기",
    "en": "Go To",
    "shortcut": "Alt+G"
  },
  "field:edit": {
    "ko": "누름틀 고치기",
    "en": "Edit Field",
    "shortcut": "Ctrl+M,K"
  },
  "field:remove": {
    "ko": "누름틀 지우기",
    "en": "Delete Field",
    "shortcut": null
  },
  "file:new-doc": {
    "ko": "새로 만들기",
    "en": "New",
    "shortcut": "Alt+N"
  },
  "file:open": {
    "ko": "열기",
    "en": "Open",
    "shortcut": null
  },
  "file:open-recent": {
    "ko": "최근 문서 열기",
    "en": "Open Recent Document",
    "shortcut": null
  },
  "file:clear-recent": {
    "ko": "최근 문서 목록 지우기",
    "en": "Clear Recent Documents",
    "shortcut": null
  },
  "file:save": {
    "ko": "저장",
    "en": "Save",
    "shortcut": "Ctrl+S"
  },
  "file:save-as": {
    "ko": "다른 이름으로 저장",
    "en": "Save As",
    "shortcut": "Ctrl+Shift+S"
  },
  "file:save-as-hwp": {
    "ko": "HWP 형식으로 저장",
    "en": "Save as HWP",
    "shortcut": null
  },
  "file:save-as-hwpx": {
    "ko": "HWPX 형식으로 저장",
    "en": "Save as HWPX",
    "shortcut": null
  },
  "file:page-setup": {
    "ko": "편집 용지",
    "en": "Page Setup",
    "shortcut": "F7"
  },
  "file:print-to-pdf": {
    "ko": "PDF로 저장",
    "en": "Save as PDF",
    "shortcut": null
  },
  "file:export-html": {
    "ko": "HTML로 내보내기",
    "en": "Export as HTML",
    "shortcut": null
  },
  "file:export-doc": {
    "ko": "Word 문서(.doc)로 내보내기",
    "en": "Export as Word document (.doc)",
    "shortcut": null
  },
  "file:print": {
    "ko": "인쇄",
    "en": "Print",
    "shortcut": "Ctrl+P"
  },
  "file:about": {
    "ko": "제품 정보",
    "en": "About",
    "shortcut": null
  },
  "format:bold": {
    "ko": "굵게",
    "en": "Bold",
    "shortcut": "Ctrl+B"
  },
  "format:italic": {
    "ko": "기울임",
    "en": "Italic",
    "shortcut": "Ctrl+I"
  },
  "format:underline": {
    "ko": "밑줄",
    "en": "Underline",
    "shortcut": "Ctrl+U"
  },
  "format:strikethrough": {
    "ko": "취소선",
    "en": "Strikethrough",
    "shortcut": null
  },
  "format:emboss": {
    "ko": "양각",
    "en": "Emboss",
    "shortcut": null
  },
  "format:engrave": {
    "ko": "음각",
    "en": "Engrave",
    "shortcut": null
  },
  "format:outline": {
    "ko": "외곽선",
    "en": "Outline",
    "shortcut": null
  },
  "format:superscript": {
    "ko": "위 첨자",
    "en": "Superscript",
    "shortcut": null
  },
  "format:subscript": {
    "ko": "아래 첨자",
    "en": "Subscript",
    "shortcut": null
  },
  "format:line-spacing": {
    "ko": "줄 간격",
    "en": "Line spacing",
    "shortcut": null
  },
  "format:line-spacing-decrease": {
    "ko": "줄 간격 줄이기",
    "en": "Decrease Line Spacing",
    "shortcut": "Alt+Shift+A"
  },
  "format:line-spacing-increase": {
    "ko": "줄 간격 늘리기",
    "en": "Increase Line Spacing",
    "shortcut": "Alt+Shift+Z"
  },
  "format:font-size-increase": {
    "ko": "글꼴 크기 크게",
    "en": "Increase Font Size",
    "shortcut": "Alt+Shift+E"
  },
  "format:font-size-decrease": {
    "ko": "글꼴 크기 작게",
    "en": "Decrease Font Size",
    "shortcut": "Alt+Shift+R"
  },
  "format:char-ratio-decrease": {
    "ko": "장평 줄이기",
    "en": "Narrow Characters",
    "shortcut": "Shift+Alt+J"
  },
  "format:char-ratio-increase": {
    "ko": "장평 늘리기",
    "en": "Widen Characters",
    "shortcut": "Shift+Alt+K"
  },
  "format:char-spacing-decrease": {
    "ko": "자간 줄이기",
    "en": "Condense Character Spacing",
    "shortcut": "Shift+Alt+N"
  },
  "format:char-spacing-increase": {
    "ko": "자간 늘리기",
    "en": "Expand Character Spacing",
    "shortcut": "Shift+Alt+W"
  },
  "format:align-left": {
    "ko": "왼쪽 정렬",
    "en": "Align Left",
    "shortcut": "Ctrl+Shift+L"
  },
  "format:align-center": {
    "ko": "가운데 정렬",
    "en": "Center",
    "shortcut": "Alt+Shift+C"
  },
  "format:align-right": {
    "ko": "오른쪽 정렬",
    "en": "Align Right",
    "shortcut": "Alt+Shift+H"
  },
  "format:align-justify": {
    "ko": "양쪽 정렬",
    "en": "Justify",
    "shortcut": "Ctrl+Shift+M"
  },
  "format:align-distribute": {
    "ko": "배분 정렬",
    "en": "Distribute",
    "shortcut": "Alt+Shift+D"
  },
  "format:align-split": {
    "ko": "나눔 정렬",
    "en": "Justify Spaces",
    "shortcut": null
  },
  "format:char-shape": {
    "ko": "글자 모양",
    "en": "Character Formatting",
    "shortcut": "Alt+L"
  },
  "format:para-shape": {
    "ko": "문단 모양",
    "en": "Paragraph Formatting",
    "shortcut": "Alt+T"
  },
  "format:apply-style": {
    "ko": "스타일 적용",
    "en": "Apply Style",
    "shortcut": null
  },
  "format:toggle-numbering": {
    "ko": "문단 번호 토글",
    "en": "Toggle Numbering",
    "shortcut": null
  },
  "format:toggle-bullet": {
    "ko": "글머리표 토글",
    "en": "Toggle Bullets",
    "shortcut": null
  },
  "format:apply-bullet": {
    "ko": "글머리표 적용",
    "en": "Apply Bullets",
    "shortcut": null
  },
  "format:para-num-shape": {
    "ko": "문단 번호 모양",
    "en": "Numbering Style",
    "shortcut": null
  },
  "format:bullet-shape": {
    "ko": "글머리표 모양",
    "en": "Bullet Style",
    "shortcut": null
  },
  "format:level-increase": {
    "ko": "한 수준 증가",
    "en": "Promote One Level",
    "shortcut": "Ctrl+Num -"
  },
  "format:level-decrease": {
    "ko": "한 수준 감소",
    "en": "Demote One Level",
    "shortcut": "Ctrl+Num +"
  },
  "format:style-dialog": {
    "ko": "스타일",
    "en": "Style",
    "shortcut": "F6"
  },
  "format:object-properties": {
    "ko": "개체 속성",
    "en": "Object Properties",
    "shortcut": "P"
  },
  "insert:hyperlink": {
    "ko": "하이퍼링크",
    "en": "Hyperlink",
    "shortcut": "Ctrl+K+H"
  },
  "hyperlink:edit": {
    "ko": "하이퍼링크 고치기",
    "en": "Edit Hyperlink",
    "shortcut": null
  },
  "hyperlink:remove": {
    "ko": "하이퍼링크 지우기",
    "en": "Delete Hyperlink",
    "shortcut": null
  },
  "insert:shape": {
    "ko": "도형",
    "en": "Shape",
    "shortcut": null
  },
  "insert:image": {
    "ko": "그림",
    "en": "Picture",
    "shortcut": null
  },
  "insert:textbox": {
    "ko": "글상자",
    "en": "Text Box",
    "shortcut": null
  },
  "insert:equation": {
    "ko": "수식",
    "en": "Equation",
    "shortcut": "Ctrl+M,M"
  },
  "insert:field": {
    "ko": "필드 입력",
    "en": "Insert Field",
    "shortcut": "Ctrl+K+E"
  },
  "insert:footnote": {
    "ko": "각주",
    "en": "Footnote",
    "shortcut": null
  },
  "insert:endnote": {
    "ko": "미주",
    "en": "Endnote",
    "shortcut": null
  },
  "insert:note-close": {
    "ko": "닫기",
    "en": "Close",
    "shortcut": null
  },
  "insert:endnote-shape": {
    "ko": "미주 모양",
    "en": "Endnote Styles",
    "shortcut": null
  },
  "insert:symbols": {
    "ko": "문자표",
    "en": "Symbol",
    "shortcut": "Alt+F10"
  },
  "insert:bookmark": {
    "ko": "책갈피",
    "en": "Bookmark",
    "shortcut": "Ctrl+K,B"
  },
  "insert:picture-props": {
    "ko": "개체 속성",
    "en": "Object Properties",
    "shortcut": null
  },
  "insert:chart-data-edit": {
    "ko": "차트 데이터 편집",
    "en": "Edit chart data",
    "shortcut": null
  },
  "insert:equation-edit": {
    "ko": "수식 편집",
    "en": "Edit equation",
    "shortcut": null
  },
  "insert:caption-toggle": {
    "ko": "캡션 넣기",
    "en": "Insert Caption",
    "shortcut": null
  },
  "insert:arrange-front": {
    "ko": "맨 앞으로",
    "en": "Bring to Front",
    "shortcut": null
  },
  "insert:arrange-forward": {
    "ko": "앞으로",
    "en": "Bring Forward",
    "shortcut": null
  },
  "insert:arrange-backward": {
    "ko": "뒤로",
    "en": "Send Backward",
    "shortcut": null
  },
  "insert:arrange-back": {
    "ko": "맨 뒤로",
    "en": "Send to Back",
    "shortcut": null
  },
  "insert:picture-delete": {
    "ko": "개체 지우기",
    "en": "Delete Object",
    "shortcut": null
  },
  "insert:group-shapes": {
    "ko": "개체 묶기",
    "en": "Group Objects",
    "shortcut": null
  },
  "insert:ungroup-shapes": {
    "ko": "개체 풀기",
    "en": "Ungroup Objects",
    "shortcut": null
  },
  "insert:rotate-cw": {
    "ko": "오른쪽 90° 회전",
    "en": "Rotate Right 90°",
    "shortcut": null
  },
  "insert:rotate-ccw": {
    "ko": "왼쪽 90° 회전",
    "en": "Rotate Left 90°",
    "shortcut": null
  },
  "insert:flip-horz": {
    "ko": "좌우 대칭",
    "en": "Flip Horizontal",
    "shortcut": null
  },
  "insert:flip-vert": {
    "ko": "상하 대칭",
    "en": "Flip Vertical",
    "shortcut": null
  },
  "page:setup": {
    "ko": "편집 용지",
    "en": "Page Setup",
    "shortcut": "F7"
  },
  "page:page-border": {
    "ko": "쪽 테두리/배경",
    "en": "Page Borders/Background",
    "shortcut": null
  },
  "page:header-create": {
    "ko": "머리말",
    "en": "Header",
    "shortcut": null
  },
  "page:footer-create": {
    "ko": "꼬리말",
    "en": "Footer",
    "shortcut": null
  },
  "page:headerfooter-close": {
    "ko": "머리말/꼬리말 닫기",
    "en": "Close Header/Footer",
    "shortcut": null
  },
  "page:headerfooter-delete": {
    "ko": "머리말/꼬리말 지우기",
    "en": "Delete Header/Footer",
    "shortcut": null
  },
  "page:headerfooter-prev": {
    "ko": "이전 머리말/꼬리말",
    "en": "Previous Header/Footer",
    "shortcut": null
  },
  "page:headerfooter-next": {
    "ko": "다음 머리말/꼬리말",
    "en": "Next Header/Footer",
    "shortcut": null
  },
  "page:new-page-num": {
    "ko": "새 번호로 시작",
    "en": "Restart Numbering",
    "shortcut": null
  },
  "page:hide-headerfooter": {
    "ko": "머리말/꼬리말 현재 쪽 감추기",
    "en": "Hide Header/Footer on This Page",
    "shortcut": null
  },
  "page:hide-current": {
    "ko": "현재 쪽만 감추기",
    "en": "Hide on Current Page Only",
    "shortcut": null
  },
  "page:insert-field-pagenum": {
    "ko": "쪽 번호 삽입",
    "en": "Insert Page Number",
    "shortcut": null
  },
  "page:insert-field-totalpage": {
    "ko": "총 쪽수 삽입",
    "en": "Insert Total Pages",
    "shortcut": null
  },
  "page:insert-field-filename": {
    "ko": "파일 이름 삽입",
    "en": "Insert File Name",
    "shortcut": null
  },
  "page:apply-hf-template": {
    "ko": "머리말/꼬리말 마당",
    "en": "Header/Footer Template",
    "shortcut": null
  },
  "page:break": {
    "ko": "쪽 나누기",
    "en": "Page Break",
    "shortcut": "Ctrl+Enter"
  },
  "page:hide": {
    "ko": "감추기",
    "en": "Hide",
    "shortcut": "Ctrl+M,S"
  },
  "page:column-break": {
    "ko": "단 나누기",
    "en": "Column Break",
    "shortcut": "Ctrl+Shift+Enter"
  },
  "page:col-1": {
    "ko": "단 - 하나",
    "en": "Columns - One",
    "shortcut": null
  },
  "page:col-2": {
    "ko": "단 - 둘",
    "en": "Columns - Two",
    "shortcut": null
  },
  "page:col-3": {
    "ko": "단 - 셋",
    "en": "Columns - Three",
    "shortcut": null
  },
  "page:col-left": {
    "ko": "단 - 왼쪽",
    "en": "Columns - Left",
    "shortcut": null
  },
  "page:col-right": {
    "ko": "단 - 오른쪽",
    "en": "Columns - Right",
    "shortcut": null
  },
  "page:col-settings": {
    "ko": "다단 설정",
    "en": "Column Settings",
    "shortcut": "Ctrl+Alt+Enter"
  },
  "page:section-settings": {
    "ko": "구역 설정",
    "en": "Section Settings",
    "shortcut": null
  },
  "table:create": {
    "ko": "표 만들기",
    "en": "Insert Table",
    "shortcut": null
  },
  "table:cell-props": {
    "ko": "표/셀 속성",
    "en": "Table/Cell Properties",
    "shortcut": null
  },
  "table:border-each": {
    "ko": "각 셀마다 적용",
    "en": "Apply to Each Cell",
    "shortcut": null
  },
  "table:border-one": {
    "ko": "하나의 셀처럼 적용",
    "en": "Apply as One Cell",
    "shortcut": null
  },
  "table:insert-row-col": {
    "ko": "줄/칸 추가하기",
    "en": "Insert Rows/Columns",
    "shortcut": "Alt+Enter"
  },
  "table:delete-row-col": {
    "ko": "줄/칸 지우기",
    "en": "Delete Rows/Columns",
    "shortcut": "Alt+Delete"
  },
  "table:insert-row-above": {
    "ko": "위쪽에 줄 추가하기",
    "en": "Insert Row Above",
    "shortcut": null
  },
  "table:insert-row-below": {
    "ko": "아래쪽에 줄 추가하기",
    "en": "Insert Row Below",
    "shortcut": null
  },
  "table:insert-col-left": {
    "ko": "왼쪽에 칸 추가하기",
    "en": "Insert Column Left",
    "shortcut": null
  },
  "table:insert-col-right": {
    "ko": "오른쪽에 칸 추가하기",
    "en": "Insert Column Right",
    "shortcut": null
  },
  "table:delete-row": {
    "ko": "줄 지우기",
    "en": "Delete Row",
    "shortcut": null
  },
  "table:delete-col": {
    "ko": "칸 지우기",
    "en": "Delete Column",
    "shortcut": null
  },
  "table:cell-split": {
    "ko": "셀 나누기",
    "en": "Split Cells",
    "shortcut": "S"
  },
  "table:cell-merge": {
    "ko": "셀 합치기",
    "en": "Merge Cells",
    "shortcut": "M"
  },
  "table:transpose-copy": {
    "ko": "행/열 바꿈 복사",
    "en": "Copy Transposed",
    "shortcut": null
  },
  "table:transpose-paste": {
    "ko": "행/열 바꿈 붙여넣기",
    "en": "Paste Transposed",
    "shortcut": null
  },
  "table:split": {
    "ko": "표 나누기",
    "en": "Split Table",
    "shortcut": "Ctrl+M,A"
  },
  "table:attach": {
    "ko": "표 붙이기",
    "en": "Attach Tables",
    "shortcut": "Ctrl+M,Z"
  },
  "table:delete": {
    "ko": "표 지우기",
    "en": "Delete Table",
    "shortcut": null
  },
  "table:caption-toggle": {
    "ko": "캡션 넣기",
    "en": "Insert Caption",
    "shortcut": null
  },
  "table:cell-height-equal": {
    "ko": "셀 높이를 같게",
    "en": "Distribute Rows Evenly",
    "shortcut": "H"
  },
  "table:cell-width-equal": {
    "ko": "셀 너비를 같게",
    "en": "Distribute Columns Evenly",
    "shortcut": "W"
  },
  "table:formula": {
    "ko": "계산식",
    "en": "Formula",
    "shortcut": "Ctrl+M,F"
  },
  "table:block-formula": {
    "ko": "블록 계산식",
    "en": "Block Formula",
    "shortcut": null
  },
  "table:thousand-sep": {
    "ko": "1,000 단위 구분 쉼표",
    "en": "Thousands separator",
    "shortcut": null
  },
  "table:decimal-add": {
    "ko": "자릿점 넣기",
    "en": "Add Thousands Separators",
    "shortcut": null
  },
  "table:decimal-remove": {
    "ko": "자릿점 빼기",
    "en": "Remove Thousands Separators",
    "shortcut": null
  },
  "tool:options": {
    "ko": "환경 설정",
    "en": "Preferences",
    "shortcut": null
  },
  "view:zoom-in": {
    "ko": "확대",
    "en": "Zoom In",
    "shortcut": "Ctrl++"
  },
  "view:zoom-out": {
    "ko": "축소",
    "en": "Zoom Out",
    "shortcut": "Ctrl+-"
  },
  "view:zoom-dialog": {
    "ko": "화면 확대/축소",
    "en": "Zoom",
    "shortcut": null
  },
  "view:zoom-fit-page": {
    "ko": "쪽 맞춤",
    "en": "Fit Page",
    "shortcut": "Ctrl+G,P"
  },
  "view:zoom-fit-width": {
    "ko": "폭 맞춤",
    "en": "Fit Width",
    "shortcut": "Ctrl+G,W"
  },
  "view:form-mode": {
    "ko": "양식 모드",
    "en": "Form Mode",
    "shortcut": null
  },
  "view:ctrl-mark": {
    "ko": "조판 부호",
    "en": "Formatting Marks",
    "shortcut": "Ctrl+G,C"
  },
  "view:para-mark": {
    "ko": "문단 부호",
    "en": "Paragraph Marks",
    "shortcut": "Ctrl+G,T"
  },
  "view:border-transparent": {
    "ko": "투명 선",
    "en": "Transparent Line",
    "shortcut": "Alt+V,T"
  },
  "view:toggle-clip": {
    "ko": "잘림 보기",
    "en": "Show Overflow",
    "shortcut": null
  },
  "view:toggle-grid": {
    "ko": "격자 보기",
    "en": "Show Grid",
    "shortcut": null
  },
  "view:grid-settings": {
    "ko": "격자 설정",
    "en": "Grid Settings",
    "shortcut": null
  },
  "view:toolbox-basic": {
    "ko": "기본",
    "en": "Basic",
    "shortcut": "Ctrl+F1"
  },
  "view:toolbox-format": {
    "ko": "서식",
    "en": "Format",
    "shortcut": null
  },
  "review:memo-insert": {
    "ko": "메모 넣기",
    "en": "Insert Memo",
    "shortcut": null
  },
  "review:memo-delete": {
    "ko": "메모 지우기",
    "en": "Delete Memo",
    "shortcut": null
  },
  "review:memo-next": {
    "ko": "다음 메모",
    "en": "Next Memo",
    "shortcut": null
  },
  "review:memo-previous": {
    "ko": "이전 메모",
    "en": "Previous Memo",
    "shortcut": null
  },
  "review:memo-show": {
    "ko": "메모 보이기/숨기기",
    "en": "Show/Hide Memos",
    "shortcut": null
  },
  "review:track-changes": {
    "ko": "변경 내용 추적",
    "en": "Track Changes",
    "shortcut": null
  },
  "review:revision-accept": {
    "ko": "변경 내용 적용",
    "en": "Accept Change",
    "shortcut": null
  },
  "review:revision-reject": {
    "ko": "변경 내용 취소",
    "en": "Reject Change",
    "shortcut": null
  },
  "review:revision-accept-all": {
    "ko": "모든 변경 내용 적용",
    "en": "Accept All Changes",
    "shortcut": null
  },
  "review:revision-reject-all": {
    "ko": "모든 변경 내용 취소",
    "en": "Reject All Changes",
    "shortcut": null
  },
  "review:revision-next": {
    "ko": "다음 변경 내용",
    "en": "Next Change",
    "shortcut": null
  },
  "review:revision-previous": {
    "ko": "이전 변경 내용",
    "en": "Previous Change",
    "shortcut": null
  },
  "review:show-markup": {
    "ko": "변경 내용 표시",
    "en": "Show Markup",
    "shortcut": null
  }
}
