/**
 * The Redrob design system (@redrob-labs/ui), re-exported for the Office apps.
 *
 * Apps import kit components from @genoffice/ui, never from @redrob-labs/ui
 * directly, so the pinned version, i18n wrapping and any Office-specific
 * composition live in one package. The kit's own IconProps is exported as
 * KitIconProps because @genoffice/ui already names an IconProps for its
 * legacy icons; the legacy one goes when those icons do.
 */
export {
  // icons
  icons,
  iconNames,
  svg,
  // foundations
  Mark,
  // actions
  Button,
  IconButton,
  Menu,
  // forms
  Input,
  Textarea,
  Select,
  Combobox,
  Checkbox,
  Radio,
  Switch,
  // navigation
  Tabs,
  Accordion,
  Scroller,
  // feedback
  Alert,
  Toast,
  Modal,
  Drawer,
  Tooltip,
  Progress,
  Loader,
  Skeleton,
  EmptyState,
  // data display
  Card,
  Badge,
  // agent chat
  Message,
  Composer,
  ComposerStatus,
  ModelPicker,
  Streaming,
  PromptSuggestions,
  AgentAction,
  AgentTimeline,
  ApprovalStep,
  Changes,
  AnswerReceipt,
  Citation,
  Disputed,
  OpinionAdded,
  // safeguards
  PrivacyProtection,
  SecondOpinionSetting,
  PRIVACY_LEVELS,
  OPINION_MODES,
  // evidence
  Redline,
  // foundations: the one moving logo
  MarkReveal,
  // frames
  AppShell,
  ThemeSwitch,
  LangSwitch,
  applyTheme,
  themeTarget,
} from '@redrob-labs/ui'

export type {
  IconName,
  IconProps as KitIconProps,
  IconComponent,
  MarkProps,
  ButtonProps,
  IconButtonProps,
  MenuProps,
  MenuItem,
  InputProps,
  TextareaProps,
  SelectProps,
  SelectOption,
  ComboboxProps,
  ComboboxOption,
  CheckboxProps,
  RadioProps,
  SwitchProps,
  TabsProps,
  TabItem,
  AccordionProps,
  AccordionItem,
  ScrollerProps,
  AlertProps,
  ToastProps,
  ModalProps,
  DrawerProps,
  TooltipProps,
  ProgressProps,
  LoaderProps,
  SkeletonProps,
  EmptyStateProps,
  CardProps,
  BadgeProps,
  MessageProps,
  ComposerProps,
  ComposerStatusProps,
  ComposerStatusItem,
  ModelPickerProps,
  StreamingProps,
  PromptSuggestionsProps,
  PromptSuggestion,
  AgentActionProps,
  AgentTimelineProps,
  AgentTimelineStep,
  ApprovalStepProps,
  ChangesProps,
  ChangeItem,
  AnswerReceiptProps,
  AnswerReceiptItem,
  CitationProps,
  DisputedProps,
  DisputedView,
  OpinionAddedProps,
  PrivacyProtectionProps,
  SecondOpinionSettingProps,
  OpinionMode,
  RedlineProps,
  RedlinePart,
  MarkRevealProps,
  AppShellProps,
  AppShellNavItem,
  ThemeSwitchProps,
  LangSwitchProps,
  LangOption,
  ThemeMode,
} from '@redrob-labs/ui'
