// The Corpus: the reference set of real .hwp/.hwpx documents that fidelity is
// measured on (spec R1, R2, R3).
//
// Documents never live in this repository (R10.5): customer and government
// files go in a directory named by HANGUL_CORPUS_DIR, described by its own
// manifest.json. A small synthetic corpus, generated by the engine itself, is
// always available so CI has something to run without the real one.

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, isAbsolute, join, resolve } from 'node:path'
import { HwpCoreDocument, type HwpFormat } from '@genoffice/hwp-core/node'

/** What a document exercises. Failures are reported per tag. */
export const CORPUS_TAGS = [
  'text',
  'table',
  'table-split',
  'multi-column',
  'header-footer',
  'master-page',
  'footnote',
  'equation',
  'picture',
  'shape',
  'textbox',
  'chart',
  'vertical-text',
  'char-spacing', // 자간
  'char-width', // 장평
  'outline-numbering', // 개요
  'numbering',
  'field',
  'memo',
  'revision',
  'password',
  'form',
  'hwp3',
] as const
export type CorpusTag = (typeof CORPUS_TAGS)[number]

export interface CorpusEntry {
  /** Stable id, used for reference and report file names. */
  id: string
  /** Path relative to the manifest, or absolute. */
  file: string
  format: HwpFormat
  tags: CorpusTag[]
  /** Where the document came from, e.g. a public URL or "customer:<org>". */
  source: string
  /** Licence or permission under which it may be used for testing. */
  permission: string
  /** Password for encrypted documents. */
  password?: string
}

export interface Corpus {
  root: string
  entries: CorpusEntry[]
}

export class CorpusError extends Error {}

export function validateManifest(raw: unknown, root: string): Corpus {
  if (!raw || typeof raw !== 'object' || !Array.isArray((raw as { entries?: unknown }).entries)) {
    throw new CorpusError('manifest.json must be an object with an "entries" array')
  }
  const seen = new Set<string>()
  const entries: CorpusEntry[] = []
  for (const [i, e] of ((raw as { entries: unknown[] }).entries).entries()) {
    const at = `entries[${i}]`
    if (!e || typeof e !== 'object') throw new CorpusError(`${at} is not an object`)
    const x = e as Record<string, unknown>
    for (const key of ['id', 'file', 'format', 'source', 'permission'] as const) {
      if (typeof x[key] !== 'string' || !(x[key] as string).trim()) throw new CorpusError(`${at}.${key} is required`)
    }
    if (x.format !== 'hwp' && x.format !== 'hwpx') throw new CorpusError(`${at}.format must be "hwp" or "hwpx"`)
    if (!/^[a-z0-9][a-z0-9._-]*$/.test(x.id as string)) throw new CorpusError(`${at}.id must be lower-case [a-z0-9._-]`)
    if (seen.has(x.id as string)) throw new CorpusError(`${at}.id "${x.id}" is duplicated`)
    seen.add(x.id as string)
    const tags = Array.isArray(x.tags) ? x.tags : []
    for (const t of tags) {
      if (!(CORPUS_TAGS as readonly string[]).includes(t as string)) throw new CorpusError(`${at}.tags has unknown tag "${t}"`)
    }
    entries.push({
      id: x.id as string,
      file: x.file as string,
      format: x.format,
      tags: tags as CorpusTag[],
      source: x.source as string,
      permission: x.permission as string,
      password: typeof x.password === 'string' ? x.password : undefined,
    })
  }
  return { root, entries }
}

export function loadCorpus(dir: string): Corpus {
  const manifest = join(dir, 'manifest.json')
  if (!existsSync(manifest)) throw new CorpusError(`no manifest.json in ${dir}`)
  return validateManifest(JSON.parse(readFileSync(manifest, 'utf8')), dir)
}

export function entryPath(corpus: Corpus, entry: CorpusEntry): string {
  return isAbsolute(entry.file) ? entry.file : resolve(corpus.root, entry.file)
}

// ── Synthetic corpus ────────────────────────────────────────────────────

interface SyntheticSpec {
  id: string
  tags: CorpusTag[]
  build(doc: HwpCoreDocument): void
}

const PARAGRAPHS = [
  '대한민국 헌법 제1조 ① 대한민국은 민주공화국이다.',
  '② 대한민국의 주권은 국민에게 있고, 모든 권력은 국민으로부터 나온다.',
  'Mixed 한글 and English text with numbers 2024, 3.14 and punctuation: 「인용」, (괄호), 가·나·다.',
]

const SYNTHETIC: SyntheticSpec[] = [
  {
    id: 'synthetic-text',
    tags: ['text'],
    build(doc) {
      let para = 0
      for (const [i, text] of PARAGRAPHS.entries()) {
        if (i > 0) para = JSON.parse(doc.raw.splitParagraph(0, para, doc.paragraphLength(0, para))).paraIdx
        doc.insertText(0, para, 0, text)
      }
    },
  },
  {
    id: 'synthetic-long',
    tags: ['text'],
    build(doc) {
      // Enough text to paginate: about four pages of body text.
      let para = 0
      for (let i = 0; i < 120; i++) {
        if (i > 0) para = JSON.parse(doc.raw.splitParagraph(0, para, doc.paragraphLength(0, para))).paraIdx
        doc.insertText(0, para, 0, `${i + 1}. ${PARAGRAPHS[i % PARAGRAPHS.length]}`)
      }
    },
  },
  {
    id: 'synthetic-table',
    tags: ['table', 'text'],
    build(doc) {
      doc.insertText(0, 0, 0, '표 1. 분기별 실적')
      const end = doc.paragraphLength(0, 0)
      const next = JSON.parse(doc.raw.splitParagraph(0, 0, end)).paraIdx
      doc.raw.createTable(0, next, 0, 3, 4)
    },
  },
  {
    id: 'synthetic-char-format',
    tags: ['text', 'char-spacing', 'char-width'],
    build(doc) {
      doc.insertText(0, 0, 0, '굵게 기울임 밑줄 자간 장평')
      doc.raw.applyCharFormat(0, 0, 0, 2, JSON.stringify({ bold: true }))
      doc.raw.applyCharFormat(0, 0, 3, 6, JSON.stringify({ italic: true }))
      doc.raw.applyCharFormat(0, 0, 7, 9, JSON.stringify({ underline: true }))
    },
  },
]

/**
 * Write the synthetic corpus (each spec in both formats) into `dir` and
 * return it. Generated by the engine, so it measures round trips and our
 * renderer's stability, never Hancom parity by itself.
 */
export function writeSyntheticCorpus(dir: string): Corpus {
  mkdirSync(dir, { recursive: true })
  const entries: CorpusEntry[] = []
  for (const spec of SYNTHETIC) {
    for (const format of ['hwp', 'hwpx'] as const) {
      const doc = HwpCoreDocument.blank()
      spec.build(doc)
      const file = `${spec.id}.${format}`
      writeFileSync(join(dir, file), doc.export(format))
      doc.dispose()
      entries.push({ id: `${spec.id}-${format}`, file, format, tags: spec.tags, source: 'synthetic:hwp-core', permission: 'generated' })
    }
  }
  const corpus = { root: dir, entries }
  writeFileSync(join(dir, 'manifest.json'), JSON.stringify({ entries }, null, 2) + '\n')
  return corpus
}

export function ensureDir(path: string): string {
  mkdirSync(dirname(path), { recursive: true })
  return path
}
